### ISSUE TITLE
use a system that allows direct use of sort-merge join without our own implementation

### ISSUE THREAD

**Issue by oschulte** [sfu-cl-lab/FactorBase#14]
makes laj code simpler (just call SQL using the right join option, or optimization option) rather than maintaining our own join code

**Comment by rmar3a** [comment]
Note: This is currently being looked at and we have a working solution, but the correctness still needs to be verified!

**Comment by rmar3a** [comment]
This has been addressed here:
https://github.com/sfu-cl-lab/FactorBase/pull/113

We use an SQL query now to do sort-merge join.  The problem before was that we created an incorrect index (we were using the "MULT" column), which prevented us from doing a more efficient join.
