### ISSUE TITLE
drop temporary CT tables

### ISSUE THREAD

**Issue by oschulte** [sfu-cl-lab/FactorBase#28]
could use a general drop procedure

+ this would save a lot of space
+ also make the output easier to read

- [x] change , to _ in Rchains. See https://github.com/sfu-cl-lab/FactorBase/blob/master/src/lattice/short_rnid_LatticeGenerator.java
- [x] try dropping tables. Should work now.

**Comment by oschulte** [comment]
Hi Zhao @JanyQZ you're right I'm missing details. Not sure what happened. Here's the kind of procedure we need.

KeepTablesOnly(connection,dbname,list of tablenames)
Inputs: 
+ connection object `connection`
+ name of database schema `dbname`
+ list of `tablenames`

Output: all tables in `dbname` are dropped *except* for the tables listed `tablenames`

Example: 

+ `dbname` = unielwin_ct
+ `tablesname` = a_ct

The only table left in unielwin_ct should be a_ct

**Comment by oschulte** [comment]
@JanyQZ Hi Jany, were you able to solve this problem? Can you please confirm that you are set up to get these messages from github?

**Comment by JanyQZ** [comment]
@oschulte Hi, Oliver, I am now working at drop_tmpTable branch. And I added a new class which named KeepTablesOnly.java. The mainly function looks like Drop_tmpTables(Connection con,String dbname,String tablename). The function is currently available to keep only one table given by the input. 
What I am thinking is that we can add a new variable to indicate the number of reserved tables and change tablename into a array, which may looks like Drop_tmpTables(Connection con,String dbname,String[] tablesname). We can talk about this issue later :)

**Comment by oschulte** [comment]
@JanyQZ sounds good! I agree with having an array of tables.

**Comment by JanyQZ** [comment]
@oschulte  Hi Oliver,  I found that we couldn't drop the table with a comma name, such as "a,b_counts", cause mysql automatically splits the sql query based on commas assuming they are separate tables and returns an error message which like "Unknown table x,xxx". I think we really need to standardize the tables names and not using commas.

**Comment by oschulte** [comment]
Hi Jany, changing table names is not a bad idea but a fair amount of work. Have you tried escaping the table name with apostrophes? E.g. `drop table `a,b_counts`` not `drop table a,b_counts`?

**Comment by JanyQZ** [comment]
@oschulte Hi, Oliver, I've already tried both of the command, it didn't work. 
Actually, it's very strange to add a comma into a table name. We should not do that at the very beginning.

**Comment by oschulte** [comment]
let's discuss with Vidhi

**Comment by JanyQZ** [comment]
@oschulte  HI, Oliver, I found a way to solve this problem. We can wrap the table name with the symbol ``, such as `a,b_counts`, it will indicate entire string is one table name. I will fix this function as soon as possible and merge into the project.

**Comment by oschulte** [comment]
okay great. Can we drop tables now?

**Comment by JanyQZ** [comment]
Of course we can! Also you can see all the commit changes in pull request. It works well.

**Comment by oschulte** [comment]
Let's review this and see if we need to add some documentation

**Comment by oschulte** [comment]
Jany posted the drop table code
