### ISSUE TITLE
Fix Functorset transfer

### ISSUE THREAD

**Issue by oschulte** [sfu-cl-lab/FactorBase#35]
Once we have resolved #34, the Rnode table no longer depends on running lattice generator.

1. Move Fnodes creation to setup.sql.
2. Move Fnodes_pvars creation to setup.sql.
3. Set Foreign key pointers for Functorset.
4. Set Foreign key points for Expansion.
5. Transfer Fnodes restricted to Functorset as NewFnodes. (Be sure to copy Rnodes with 2nodes as required)
6. Transfer 1nodes etc. restricted to Fnodes

**Comment by oschulte** [comment]
Also create view in _bn where BN_DAG = edges from maximal rchain

**Comment by vidhiJain** [comment]
In point 6, do we have to move the 1nodes etc. restricted to Fnodes instead of FunctorSet?

**Comment by oschulte** [comment]
let's discuss today after fixing the rnid issue
