### ISSUE TITLE
reclaim rnid from Lattice Generator

### ISSUE THREAD

**Issue by oschulte** [sfu-cl-lab/FactorBase#43]
LatticeGenerator should have been rewritten so that instead of messing up `rnid` in `Rnodes`, it works with a copy `shortrnid` of `rnid`. Here's a suggestion.

1. in [LatticeGenerator](https://github.com/sfu-cl-lab/FactorBase/wiki/short_rnid_LatticeGenerator), replace start by copying Rnodes to a temporary table called LatticeRnodes. E.g.
      + `create table LatticeRNodes as select * from RNodes `.
2. Replace all references to `Rnodes` table by `LatticeRnodes`. The lattice generator is free to mess up the `LatticeRnodes`.
3. change the column name `lattice_membership.name` to `lattice_membership.Rchain`. 
4. Using the lattice-fix script, change the column names `lattice_membership.orig_rnid` to `lattice_membership.member.rnid` and `lattice_rel.orig_rnid` to `lattice_rel.rnid_removed`.

**Comment by vidhiJain** [comment]
In [LatticeGenerator,](https://github.com/sfu-cl-lab/FactorBase/wiki/short_rnid_LatticeGenerator), the rnid (i.e. short rnid) are populated. Before running LatticeGenerator, the rnid column is entirely NULL. 

So here is the current flow of information in RNodes table:
1. MakeSetup.java creates a table RNodes in `<db>_setup` and populates all the fields but leaves rnid as NULL.
2. transfer.sql creates a copy of RNodes  from `<db>_setup`  to `<db>_BN` .
3. short_rnid_LatticeGenerator.java, first of all, populates the rnid column of the table RNodes in `<db>_BN` and then performs its work.

**Comment by oschulte** [comment]
thanks!
