### ISSUE TITLE
should we migrate information from Bayes Base website to github?

### ISSUE THREAD

**Issue by oschulte** [sfu-cl-lab/FactorBase#7]
I think it would be nice to have the main webpages all come from github rather than here. 

 http://www.cs.sfu.ca/~oschulte/BayesBase/BayesBase.html

For one thing, it's easier to share the editing. We can still use BayesBase to host bigger files, e.g. datasets.

**Comment by oschulte** [comment]
The first thing to migrate would the configuration information

**Comment by vidhiJain** [comment]
The configuration information is now displayed as screenshot on README.

**Comment by vidhiJain** [comment]
Is there any other information from the BayesBase website that should be on FactorBase README?

**Comment by zeruniverse** [comment]
I would suggest to have a GitHub page for this project rather than moving all stuffs to README. I can do the migration if @oschulte sends me the website source file.

**Comment by oschulte** [comment]
Thanks Vidhi and Jeffrey. Yes Jeffrey is right about making a github page. It would be great if he can move the info!!!!! 

There are two things I think: 

1. The project repositories with the implemented tools for different functionalities. We discussed making different repositories so the tools are easier to maintain and to use. I think this was actually @zeruniverse 's idea. The readmes are close to the code so they can focus on the details of how to run the code. 

2. The project website. This should be a showcase explaining the background, showing examples, datasets, discussion of issues etc. The github readmes can be linked to for users who want to run things. Repetition does not hurt, for instance the output formats in the FactorBase readme could be repeated so project visitors see all the cool things we can do. 

I'll see if I can attach the website files. Thanks again for offering to help!

**Comment by zeruniverse** [comment]
Done
